### ISSUE TITLE
Specialisms for list items described in the Material Design spec

### ISSUE THREAD

**Issue by WrinklyNinja** [Polymer/paper-item#21]
I've put together some CSS overrides that make paper-item conform better to the Material Design spec when used for one- and two-line list items with icons, and I think such specialisms may be useful to have upstream, but I'm unsure of how to implement them in a PR that's generally useful and conforms to Polymer's style.

At the moment I've got something like

```
<paper-item class="two-line">
  <core-icon class="avatar" icon="..."></core-icon>
  <div class="text">
    <div class="primary">...</div>
    <div class="secondary">...</div>
  </div>
  <core-icon icon="..."></core-icon>
</paper-item>
```

with styling for each of the classes (and a `core-icon:first-child` to add a right margin).

Should I be using attributes for styling instead of classes (Polymer seems to prefer doing so)? Any other advice?

**Comment by morethanreal** [comment]
I think it would be useful to create specialized elements for the various item types. For example, a `<paper-two-line-item>` might look like this:

```
<polymer-element name="paper-two-line-item" extends="paper-button-base" attributes="icon iconSrc">
<template>
  <style>
    /* styles here */
  </style>
  <template if="{{icon || iconSrc}}">
    <core-icon icon="{{icon}}" src="{{iconSrc}}"></core-icon>
  </template>
  <div class="button-content" relative layout horizontal center>
    <content select=".primary"></content>
    <content select=".secondary"></content>
  </div>
</template>
</polymer-element>
```

**Comment by Ortham** [comment]
Closing this as it's obsolete.
